### ISSUE TITLE
Bug Set MASK +7 ### ###-##-##" and text "9876543210"

### ISSUE THREAD

**Issue by DemaFay** [MihaelIsaev/MaskedEditTextWatcher#1]
My mask is "+7 ### ###-##-##"

and i setText to My EditText "9876543210" and expect to receive +7 987 654-32-10. but return "+7 876 543-21-0"

because of

private String unmask(String s, String countryCode) { //s = "9876543210" countryCode="+7"
        s = s.replace("+", ""); //s = "9876543210"
        s = s.substring(countryCode.replace("+", "").length()); //  !!! s = "876543210" !!!
        s = s.replaceAll("\\D", "");
        return s;
}

that's how it works normally

private String unmask(String s, String countryCode) {
        s = s.replace("+", "");
        String countryCodeTmp = countryCode.replace("+", "");
        if (s.substring(0, countryCodeTmp.length()).equals(countryCodeTmp)) { //check contains country code in the text
            s = s.substring(countryCodeTmp.length());
        }
        s = s.replaceAll("\\D", "");
        return s;
    }

**Comment by MihaelIsaev** [comment]
Could you please send a pull request?
